### ISSUE TITLE
RetinaNet ResNeXt-50 ONNX Model GS Does Not Work

### ISSUE THREAD

**Issue by leimao** [NVIDIA/Deep-Learning-Accelerator-SW#9]
The [RetinaNet ResNeXt-50](https://github.com/NVIDIA/Deep-Learning-Accelerator-SW/tree/main/scripts/prepare_models#retinanet-resnext-50) `python3 retinanet_resnext50.py` failed to execute.

```bash
$ python3 retinanet_resnext50.py
Traceback (most recent call last):
  File "retinanet_resnext50.py", line 50, in <module>
    main()
  File "retinanet_resnext50.py", line 36, in main
    common.extract_subgraph(graph, input_names, output_names, input_shape)
  File "/mnt/scripts/prepare_models/common.py", line 96, in extract_subgraph
    tensor.shape[0] = input_shape[0]
IndexError: list assignment index out of range
```

After some triage, still got some errors.

```bash
$ python3 retinanet_resnext50.py
Traceback (most recent call last):
  File "retinanet_resnext50.py", line 50, in <module>
    main()
  File "retinanet_resnext50.py", line 41, in main
    common.to_resize_with_scales(graph)
AttributeError: module 'common' has no attribute 'to_resize_with_scales'
```

**Comment by nvoliver** [comment]
fixed with https://github.com/NVIDIA/Deep-Learning-Accelerator-SW/commit/38a033658d64e232558ceedae00b37425f706c68 (common.py was missed in the latest update), thanks for pointing this out.
